"""make vector_data nullable

Revision ID: 1560cd5ae2c1
Revises: abc123
Create Date: 2025-08-04 19:44:30.723799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1560cd5ae2c1'
down_revision: Union[str, None] = 'abc123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.alter_column('vector_data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('vector_data',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
