"""reverting recent edits to document and embedding models

Revision ID: a15519b4323d
Revises: 1c5cb6886abb
Create Date: 2025-08-04 17:43:11.590952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15519b4323d'
down_revision: Union[str, None] = '1c5cb6886abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_chunks_document_id_fkey', 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    op.drop_constraint('embeddings_chunk_id_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'document_chunks', ['chunk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key('embeddings_chunk_id_fkey', 'embeddings', 'document_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key('document_chunks_document_id_fkey', 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
